### ISSUE TITLE
连续消息合并开启后，撤回第一条影响头像显示

### ISSUE THREAD

**Issue by GoForceX** [MUKAPP/BetterQQNT-MSpring-Theme#36]
同一人连续多条消息发出后，撤回第一条会导致发送人头像与昵称不显示

对于自己发送的消息和他人发送的消息都会触发此bug

# 环境

QQ: v9.9.1-15820
LiteLoader: v0.5.0 (Commit ac0799b9)
MSpring: v1.1.2

# 复现方法

1. 连续发送多条消息
2. 撤回第一条消息

# 效果

![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/67143590/b9e468dd-4aa1-4e72-938c-fcc53b8b013c)

**Comment by GoForceX** [comment]
用 devtools 看了一眼，可能是因为在撤回的时候不会触发 MutationObserver，导致撤回时头像和昵称随消息一起消失（？）

btw, 在安装了 LLAPI 的情况下还会报个错，不知道是否有关

```
​Uncaught TypeError: Cannot read properties of undefined (reading 'forEach')
    at llqqnt://local-file/C:\Users\<Username>\Documents\LiteLoaderQQNT\plugins\LiteLoaderQQNT-Plugin-LLAPI-main/./src/renderer.js:568:34
    at NodeList.forEach (<anonymous>)
    at MutationObserver.<anonymous> (llqqnt://local-file/C:\Users\<Username>\Documents\LiteLoaderQQNT\plugins\LiteLoaderQQNT-Plugin-LLAPI-main/./src/renderer.js:556:37)
```
