### ISSUE TITLE
mac安装包异常

### ISSUE THREAD

**Issue by xzajyjs** [MUKAPP/BetterQQNT-MSpring-Theme#65]
arm Mac
```
Error: Bad archive
at FsRead.readUntilFoundCallback [as callback] (/Users/xzajyjs/Library/Containers/com.tencent.qq/Data/Documents/LiteLoader/plugins/pluginStore/node_modules/node-stream-zip/node_stream_zip.js:203:39)
at FsRead.readCallback (/Users/xzajyjs/Library/Containers/com.tencent.qq/Data/Documents/LiteLoader/plugins/pluginStore/node_modules/node-stream-zip/node_stream_zip.js:996:25)
at FSReqCallback.wrapper [as oncomplete] (node:fs:684:5)
```
"安装包异常，可能是作者未正确配置"

**Comment by MUKAPP** [comment]
检查一下网络

**Comment by xzajyjs** [comment]
网络没有问题，全局也没用

**Comment by MUKAPP** [comment]
其他插件可以下载吗

**Comment by xzajyjs** [comment]
都是可以的

**Comment by MUKAPP** [comment]
建议多尝试几次
![image](https://github.com/MUKAPP/LiteLoaderQQNT-MSpring-Theme/assets/41848070/7fa9537f-ac09-4392-8842-911a5901bce2)
