### ISSUE TITLE
此主题在9.9.15-26702版本无法使用

### ISSUE THREAD

**Issue by bocchi810** [MUKAPP/BetterQQNT-MSpring-Theme#98]
#### 错误信息：
```
[Main] Unexpected token '�', "����������"... is not valid JSON
SyntaxError: Unexpected token '�', "����������"... is not valid JSON
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (C:\Users\Administartor\Documents\LiteloaderQQNT\plugins\LiteLoaderQQNT-MSpring-Theme\main.js:197:25)
    at Module._compile (node:internal/modules/cjs/loader:1373:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1432:10)
    at Module.load (node:internal/modules/cjs/loader:1215:32)
    at Module._load (node:internal/modules/cjs/loader:1031:12)
    at f._load (node:electron/js2c/node_init:2:18640)
    at Module.require (node:internal/modules/cjs/loader:1240:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.init (C:\LiteloaderQQNT\src\loader_core\main.js:13:43)
```
#### 环境信息：
```
{"qqnt":"9.9.15-26702","liteloader":"1.2.0","node":"20.14.0","chrome":"126.0.6478.36","electron":"31.0.1","platform":"win32"}
```

**Comment by MUKAPP** [comment]
删除配置文件试试
`C:\Users\Administartor\Documents\LiteloaderQQNT\data\mspring_theme\settings.json`

**Comment by bocchi810** [comment]
> 删除配置文件试试 `C:\Users\Administartor\Documents\LiteloaderQQNT\data\mspring_theme\settings.json`

好了，可以了
